spring:
  application:
    name: Poseidon
  datasource:
    url: jdbc:mysql://127.0.0.1/poseidon
    username: root
    password: 123456
server:
  port: 8000


poseidon:
  secret: 123456789
  conf:
    dir:
  access:
    token: